package com.softwaredna.analysis.workspace;

import com.softwaredna.common.exception.ApiException;
import com.softwaredna.common.exception.ErrorCode;
import com.softwaredna.config.WorkspaceProperties;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

/**
 * Creates and reclaims analysis workspaces.
 *
 * <p>The workspace root is fixed by configuration; a client never supplies a
 * path, and the only variable part of a workspace location is an analysis
 * UUID generated by this service.
 */
@Component
public class WorkspaceManager {

    private static final Logger log = LoggerFactory.getLogger(WorkspaceManager.class);

    private final WorkspaceProperties properties;
    private Path root;

    public WorkspaceManager(WorkspaceProperties properties) {
        this.properties = properties;
    }

    @PostConstruct
    public void prepareRoot() {
        try {
            root = Path.of(properties.root()).toAbsolutePath().normalize();
            Files.createDirectories(root);
            log.info("Analysis workspace root: {}", root);
            reclaimOrphans();
        } catch (IOException e) {
            throw new UncheckedIOException("Could not prepare the workspace root", e);
        }
    }

    /** Creates an empty workspace for one analysis. */
    public AnalysisWorkspace create(UUID analysisId) {
        Path workspaceRoot = root.resolve(analysisId.toString());
        if (!workspaceRoot.normalize().startsWith(root)) {
            // Unreachable with a real UUID, but the invariant is worth asserting
            // because everything downstream trusts it.
            throw new ApiException(ErrorCode.INTERNAL_ERROR, "Invalid workspace location.");
        }
        try {
            AnalysisWorkspace.deleteRecursively(workspaceRoot);
            Files.createDirectories(workspaceRoot);
            return new AnalysisWorkspace(analysisId, workspaceRoot, properties.keepAfterAnalysis());
        } catch (IOException e) {
            throw new ApiException(ErrorCode.ANALYSIS_FAILED,
                    "Could not prepare a workspace for the analysis.", e);
        }
    }

    /**
     * Removes workspaces left behind by a previous run. Analyses do not survive
     * a restart, so anything already here is dead.
     */
    private void reclaimOrphans() throws IOException {
        if (properties.keepAfterAnalysis() || !Files.isDirectory(root)) {
            return;
        }
        try (var entries = Files.list(root)) {
            entries.filter(Files::isDirectory).forEach(entry -> {
                try {
                    AnalysisWorkspace.deleteRecursively(entry);
                    log.info("Reclaimed orphaned workspace {}", entry.getFileName());
                } catch (IOException e) {
                    log.warn("Could not reclaim workspace {}", entry.getFileName());
                }
            });
        }
    }
}
